CREATE CATALOG IF NOT EXISTS sales_dwh;

USE CATALOG sales_dwh;

CREATE SCHEMA IF NOT EXISTS sales_dwh.bronze;

CREATE SCHEMA IF NOT EXISTS sales_dwh.silver;

CREATE SCHEMA IF NOT EXISTS sales_dwh.gold;

SHOW SCHEMAS IN sales_dwh;