name: Sync to Databricks Git Folder
on:
  push:
    branches:
      - main

jobs:
  update-databricks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Update Databricks Git Folder
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks repos update "/Workspace/Sales Data warehouse/Retail-Sales-Data-Warehouse-project" --branch main 
          